import * as THREE from 'three';import {OrbitControls} from './vendor/OrbitControls.js';
import {readArtwork,quantizePixels} from './src/image.js';import {make3MF,makeSTL} from './src/export.js';
const $=id=>document.getElementById(id);let currentFile=null,art=null,segmented=null,model=null,job=0,readJob=0,buildTimer,currentView='front';
const worker=new Worker(new URL('./geometry-worker.js',import.meta.url),{type:'module'});
const controlsIDs=['size','thickness','smoothing','colors','spacing','shiftX','shiftY'];
function outputs(){for(const id of controlsIDs){const unit=id==='colors'?'':' mm';$(id+'Value').textContent=$(id).value+unit;}for(const id of ['spacing','shiftX','shiftY'])$(id).disabled=$('autoMount').checked;}
function status(text,kind=''){$('status').textContent=text;$('status').className='status '+kind;}
function busy(text){$('processing').hidden=false;$('processingText').textContent=text;$('export3mf').disabled=$('exportStl').disabled=true;}
let renderer,scene,camera,orbit,meshGroup,grid;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xffffff,0);$('viewport').append(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(38,1,.1,3000);camera.up.set(0,1,0);orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.minDistance=40;orbit.maxDistance=700;orbit.target.set(0,0,0);const ambient=new THREE.HemisphereLight(0xfffbf2,0x708879,2.2);scene.add(ambient);for(const [pos,power]of [[[0,50,-180],2.8],[[100,100,180],2.4],[[-100,-80,40],1]]){const l=new THREE.DirectionalLight(0xffffff,power);l.position.set(...pos);scene.add(l);}grid=new THREE.GridHelper(260,26,0xadbba9,0xd7dfcf);grid.rotation.x=Math.PI/2;grid.position.z=-.12;grid.material.transparent=true;grid.material.opacity=.35;scene.add(grid);new ResizeObserver(()=>{const r=$('viewport').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}).observe($('viewport'));const frame=()=>{requestAnimationFrame(frame);orbit.update();renderer.render(scene,camera);};frame();setView('front');}catch(e){status('Your browser cannot display WebGL. Generation and downloads are still available.','warning');}
function clearGroup(){if(!meshGroup)return;scene.remove(meshGroup);meshGroup.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose();});}
function showModel(result){if(!scene)return;clearGroup();meshGroup=new THREE.Group();for(const p of result.parts){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p.positions,3));g.setIndex(new THREE.BufferAttribute(p.triangles,1));g.computeVertexNormals();const material=new THREE.MeshStandardMaterial({color:p.color,roughness:.66,metalness:0,side:THREE.FrontSide});meshGroup.add(new THREE.Mesh(g,material));}scene.add(meshGroup);setView(currentView);}
function setView(view){currentView=view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('viewCaption').textContent=view==='front'?'Front view · colors face the print bed':view==='back'?'Rear view · rounded arches print last':'Angled view · hidden rear string arches';if(!camera)return;const b=model?.bounds??{min:[-50,-50,0],max:[50,50,11]},cx=(b.min[0]+b.max[0])/2,cy=(b.min[1]+b.max[1])/2,cz=(b.min[2]+b.max[2])/2;let extent=Math.max(b.max[0]-b.min[0],b.max[1]-b.min[1],80),d=extent*1.95;if(camera.aspect<1)d/=camera.aspect;orbit.target.set(cx,cy,cz);const pos=view==='front'?[cx,cy,cz-d]:view==='back'?[cx,cy,cz+d]:[cx+d*.63,cy+d*.32,cz+d*.82];camera.position.set(...pos);grid.visible=view!=='front';orbit.update();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function drawPalette(){const box=$('palette');box.replaceChildren();segmented.palette.forEach((c,i)=>{const label=document.createElement('label');label.title='Color '+(i+1)+': '+c;const input=document.createElement('input');input.type='color';input.value=c;input.setAttribute('aria-label','Artwork color '+(i+1));input.oninput=()=>{segmented.palette[i]=input.value.toUpperCase();scheduleBuild();};label.append(input);box.append(label);});}
function segment(){if(!art)return;segmented=quantizePixels(art.rgba,Number($('colors').value),art.originalPalette);drawPalette();scheduleBuild();}
async function loadFile(file){const token=++readJob;++job;clearTimeout(buildTimer);art=segmented=null;window.__lastModel=null;currentFile=file;$('fileName').textContent=file.name;model=null;busy('Reading your artwork…');status('Preparing colors and outline…');try{const loaded=await readArtwork(file,{removeBg:$('removeBg').checked,n:768});if(token!==readJob)return;art=loaded;segment();}catch(e){if(token!==readJob)return;$('processing').hidden=true;status(e.message,'error');}}
function scheduleBuild(){++job;window.__lastModel=null;clearTimeout(buildTimer);if(!segmented)return;model=null;$('export3mf').disabled=$('exportStl').disabled=true;buildTimer=setTimeout(build,220);}
function build(){outputs();const id=job;busy('Finding solid attachment points…');status('Generating a printable model…');worker.postMessage({id,input:{labels:segmented.labels,n:art.n,palette:segmented.palette.slice(),size:Number($('size').value),thickness:Number($('thickness').value),smoothing:Number($('smoothing').value),mount:{auto:$('autoMount').checked,spacing:Number($('spacing').value),x:Number($('shiftX').value),y:Number($('shiftY').value)}}});}
worker.onmessage=({data})=>{if(data.id!==job)return;if(data.status){$('processingText').textContent=data.status+'…';return;}$('processing').hidden=true;if(data.error){model=null;status(data.error,'error');return;}model=data.result;$('empty').style.display='none';showModel(model);const w=model.bounds.max[0]-model.bounds.min[0],h=model.bounds.max[1]-model.bounds.min[1];$('dimensions').textContent=w.toFixed(1)+' × '+h.toFixed(1)+' mm';$('height').textContent=(model.bounds.max[2]-model.bounds.min[2]).toFixed(1)+' mm';$('colorCount').textContent=model.parts.length;$('placement').textContent=(model.placement.balanced?'Auto placed':'Manual placement')+' · '+model.placement.spacing.toFixed(1)+' mm apart';for(const id of ['shiftX','shiftY']){$(id).min=-Math.ceil(Number($('size').value)/2);$(id).max=Math.ceil(Number($('size').value)/2);}if(model.placement.balanced){const [a,b]=model.placement.centers;$('spacing').value=Math.round(model.placement.spacing);$('shiftX').value=Math.round((a[0]+b[0])/2);$('shiftY').value=Math.round(a[1]);outputs();}if(model.components>1)status('This artwork makes '+model.components+' disconnected pieces. Check their connections before hanging.','warning');else status('Geometry checked · ready to export.');$('export3mf').disabled=$('exportStl').disabled=false;window.__lastModel=model;};
worker.onerror=e=>{$('processing').hidden=true;status('The geometry engine could not load. Serve this folder over HTTP or use GitHub Pages.','error');};
$('fileInput').onchange=()=>{if($('fileInput').files[0])loadFile($('fileInput').files[0]);};const drop=$('dropzone');for(const evt of ['dragenter','dragover'])drop.addEventListener(evt,e=>{e.preventDefault();drop.classList.add('dragging');});for(const evt of ['dragleave','drop'])drop.addEventListener(evt,e=>{e.preventDefault();drop.classList.remove('dragging');});drop.addEventListener('drop',e=>{if(e.dataTransfer.files[0])loadFile(e.dataTransfer.files[0]);});
let exampleRequest=0;
async function loadExample(name){const request=++exampleRequest;busy('Loading the '+name+' example…');try{const r=await fetch('./examples/'+name+'.svg');if(!r.ok)throw Error('The example could not be loaded.');const blob=await r.blob();if(request!==exampleRequest)return;loadFile(new File([blob],name+'.svg',{type:'image/svg+xml'}));}catch(e){if(request!==exampleRequest)return;$('processing').hidden=true;status(e.message,'error');}}
function example(){return loadExample('flower');}
document.querySelectorAll('[data-sample]').forEach(button=>button.onclick=()=>loadExample(button.dataset.sample));
$('example').onclick=$('emptyExample').onclick=example;$('removeBg').onchange=()=>{if(currentFile)loadFile(currentFile);};for(const id of ['size','thickness','smoothing','spacing','shiftX','shiftY'])$(id).oninput=()=>{outputs();scheduleBuild();};$('colors').oninput=()=>{outputs();segment();};$('autoMount').onchange=()=>{outputs();$('manualDetails').open=!$('autoMount').checked;scheduleBuild();};$('manualDetails').addEventListener('toggle',()=>{if($('manualDetails').open&&$('autoMount').checked){$('autoMount').checked=false;outputs();scheduleBuild();}});
function save(data,ext,mime){const url=URL.createObjectURL(new Blob([data],{type:mime})),a=document.createElement('a');a.href=url;a.download=(currentFile?.name.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]/g,'_')||'wall-hanger')+'-wall-hanger.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
$('export3mf').onclick=async()=>{if(!model)return;const snapshot=model;$('export3mf').disabled=true;status('Packing the color 3MF…');try{const bytes=await make3MF(snapshot,()=>new window.JSZip(),currentFile?.name||'Wall hanger');save(bytes,'3mf','application/vnd.ms-package.3dmanufacturing-3dmodel+xml');status('3MF downloaded. Assign filaments and slice in Bambu Studio.');}catch(e){status('Export failed: '+e.message,'error');}finally{if(model)$('export3mf').disabled=false;}};
$('exportStl').onclick=()=>{if(!model)return;save(makeSTL(model),'stl','model/stl');status('STL downloaded. STL carries geometry only.');};outputs();
