const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const num=n=>Number(n.toFixed(6));
export async function make3MF(model,zipFactory,title='Custom SVG wall hanger'){
 const materials=model.parts.map(p=>`<base name="${esc(p.name)}" displaycolor="${p.color}FF"/>`).join('');
 const objects=model.parts.map((p,i)=>{const vertices=[];for(let j=0;j<p.positions.length;j+=3)vertices.push(`<vertex x="${num(p.positions[j])}" y="${num(p.positions[j+1])}" z="${num(p.positions[j+2])}"/>`);const triangles=[];for(let j=0;j<p.triangles.length;j+=3)triangles.push(`<triangle v1="${p.triangles[j]}" v2="${p.triangles[j+1]}" v3="${p.triangles[j+2]}"/>`);return `<object id="${i+2}" type="model" name="${esc(p.name)}" pid="1" pindex="${i}"><mesh><vertices>${vertices.join('')}</vertices><triangles>${triangles.join('')}</triangles></mesh></object>`;}).join('');
 const assemblyID=model.parts.length+2;const components=model.parts.map((_,i)=>`<component objectid="${i+2}"/>`).join('');
 const xml=`<?xml version="1.0" encoding="UTF-8"?><model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"><metadata name="Title">${esc(title)}</metadata><metadata name="Description">Face-down multicolor inlay wall hanger with compact rear string arches. Unsliced geometry; map filaments and slice before printing.</metadata><resources><basematerials id="1">${materials}</basematerials>${objects}<object id="${assemblyID}" type="model" name="Wall hanger"><components>${components}</components></object></resources><build><item objectid="${assemblyID}"/></build></model>`;
 const zip=zipFactory();zip.file('3D/3dmodel.model',xml);zip.file('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>');zip.file('_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>');return zip.generateAsync({type:'uint8array',compression:'DEFLATE'});
}
export function makeSTL(model){const parts=model.stlMesh?[model.stlMesh]:model.parts;const count=parts.reduce((s,p)=>s+p.triangles.length/3,0),data=new ArrayBuffer(84+50*count),view=new DataView(data);view.setUint32(80,count,true);let off=84;for(const p of parts)for(let i=0;i<p.triangles.length;i+=3){const vs=[p.triangles[i],p.triangles[i+1],p.triangles[i+2]].map(v=>[p.positions[v*3],p.positions[v*3+1],p.positions[v*3+2]]),a=vs[1].map((v,j)=>v-vs[0][j]),b=vs[2].map((v,j)=>v-vs[0][j]),normal=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],l=Math.hypot(...normal)||1;[normal.map(v=>v/l),...vs].flat().forEach((v,j)=>view.setFloat32(off+j*4,v,true));off+=50;}return new Uint8Array(data);}
